name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@engine262'
          always-auth: true # required if using yarn
      - run: git submodule update --init --recursive
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test
        env:
          CONTINUOUS_INTEGRATION: 1
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
      - run: |
          git config --global user.email "gha@example.com"
          git config --global user.name "GHA"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git fetch github
          git checkout gh-pages
          cp dist/engine262.js engine262.js
          cp dist/engine262.js.map engine262.js.map
          git add engine262.js engine262.js.map
          git commit -m "autobuild" || exit 0 # exit silently if nothing changed
          git push -u github gh-pages
        env:
          GITHUB_TOKEN: ${{github.token}}
